name: MSBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"
          
      - name: Set environment variables
        run: |
          echo "QtMsBuild=${{ env.QT_ROOT_DIR }}\\bin" >> $GITHUB_ENV

      - run: |
          curl.exe -o 'qtvstools.vsix' -L 'https://marketplace.visualstudio.com/_apis/public/gallery/publishers/TheQtCompany/vsextensions/QtVisualStudioTools2022/3.3.1.1/vspackage'
          
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe' /q /logFile:qtvstools.log qtvstools.vsix

          Get-Content ${env:TEMP}\qtvstools.log

#      - shell: bash
#        run: echo "QtMsBuild = $QtMsBuild"

#      - shell: bash
#        run: find /c \( -name '*.targets' -o -name '*.props' \)
      
