name: MSBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"
          
      - name: Set environment variables
        run: |
          echo "QtMsBuild=${{ env.QT_ROOT_DIR }}\\bin" >> $GITHUB_ENV
          
      - shell: cmd
        run: set

      - shell: bash
        run: ls -la $QtMsBuild/

      - shell: bash
        run: find $QT_ROOT_DIR \( -name '*.targets' -o -name '*.props' \)
      
